import type { CodeGenerator, CommonSegment, Route } from 'soonloh';
import { utils } from 'soonloh';
import path from 'node:path';

interface Options {
  root: string;
  targetPath?: (pathSafeBranch: string) => string;
}

export interface RouteNode {
  segment: CommonSegment;
  namedRouteFiles: Record<string, Route<CommonSegment>>;
  children: Record<string, RouteNode>;
}

export function genSolidRouter({
  root,
  targetPath = () => 'src/shared/routes/definition.ts',
}: Options): CodeGenerator<CommonSegment> {
  return {
    name: 'solid-router',
    targetPath,
    generate(routes, resolvedTargetPath) {
      const tree = utils.makeRouteTree(routes);
      const resolveFile = (s: string) =>
        path.posix.relative(
          path.posix.dirname(resolvedTargetPath),
          path.posix.join(root, s),
        );

      const generateRoute = (
        { namedRouteFiles: { layout, page }, ...node }: RouteNode,
        indent: number,
      ): string => {
        const route = (() => {
          switch (node.segment.kind) {
            case 'grouping':
            case 'terminator':
              return ['/'];
            case 'static':
              return [node.segment.path];
            case 'param':
              if (node.segment.catchall) {
                return [`*${node.segment.name}`];
              } else if (node.segment.optional) {
                return [`:${node.segment.name}?`];
              } else {
                return [`:${node.segment.name}`];
              }
          }
        })();

        const wrapLayout = layout
          ? (s: string) =>
              [
                `{`,
                `  path: ${JSON.stringify(route)},`,
                `  component: lazy(() => import(${JSON.stringify(
                  resolveFile(layout.filePosix),
                )})),`,
                `  children: [`,
                s,
                `  ],`,
                `},`,
              ]
                .filter(Boolean)
                .flatMap((s) => s.split('\n'))
                .map((s) => '  '.repeat(indent) + s)
                .join('\n')
          : (s: string) => s;

        return wrapLayout(
          [
            page &&
              [
                `{`,
                `  path: ${
                  layout ? JSON.stringify(['/']) : JSON.stringify(route)
                },`,
                `  component: lazy(() => import(${JSON.stringify(
                  resolveFile(page.filePosix),
                )})),`,
                `},`,
              ]
                .filter(Boolean)
                .flatMap((s) => s.split('\n'))
                .map((s) => '  '.repeat(indent + (layout ? 1 : 0)) + s)
                .join('\n'),
            ...Object.values(node.children).map((child) =>
              generateRoute(child, indent + (layout ? 1 : 0)),
            ),
          ].join('\n'),
        );
      };

      return [
        `// WARNING: do not edit this file directly`,
        `//          the content is auto-generated.`,
        ``,
        `import { lazy } from 'solid-js'`,
        `import type { RouteDefinition } from '@solidjs/router'`,
        ``,
        `export const GeneratedRoutes = [`,
        generateRoute(tree.root, 1),
        `] satisfies RouteDefinition[];`,
        ``,
      ].join('\n');
    },
  };
}
