// WARNING: do not edit this file directly
//          the content is auto-generated.

import { lazy } from 'solid-js'
import type { RouteDefinition } from '@solidjs/router'

export const GeneratedRoutes = [
  {
    path: ["/"],
    component: lazy(() => import("../../app/page.tsx")),
  },
  {
    path: ["admin"],
    component: lazy(() => import("../../app/admin/layout.tsx")),
    children: [
      {
        path: ["/"],
        component: lazy(() => import("../../app/admin/page.tsx")),
      },
    ],
  },
] satisfies RouteDefinition[];
